import React from 'react';
import {AbsoluteFill,Composition,Sequence,OffthreadVideo,registerRoot,staticFile,useCurrentFrame,interpolate,Easing} from 'remotion';
import clips from './shots.json';
const FPS=30;
const names={CourseSetup:'IT5004 / Course setup and student question',ContinuingSupport:'IT5004 / Event-driven support',InstructorReview:'IT5004 / Instructor review'};
function Cursor({click,t}:{click:any,t:number}){if(!click)return null;const [x,y,at]=click;if(t<at-1||t>at+.6)return null;const q=interpolate(t,[at-1,at],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});const r=(t-at)/.4;return <div style={{position:'absolute',left:x-100*(1-q),top:y+60*(1-q),pointerEvents:'none'}}>{r>0&&r<1&&<div style={{position:'absolute',left:-20*r,top:-20*r,width:40*r,height:40*r,border:'3px solid #6e60ea',borderRadius:'50%',opacity:1-r}}/>}<svg width="22" height="29" viewBox="0 0 23 30"><path d="M2 1 L2 23 L8 18 L13 28 L17 26 L12 16 L21 15 Z" fill="#171923" stroke="white" strokeWidth="1.5"/></svg></div>}
function Shot({shot,suite}:{shot:any,suite:string}){const t=useCurrentFrame()/FPS;const [bx,by,bw,bh]=shot.box;const zoom=Math.min(1600/bw,900/bh);const ease=shot.move?interpolate(t,[0,1.3],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.cubic)}):1;const z=zoom*(.94+.06*ease);const x=800-(bx+bw/2)*z,y=450-(by+bh/2)*z;return <AbsoluteFill style={{background:'#edf0f4',fontFamily:'Arial,sans-serif'}}><div style={{position:'absolute',left:160,top:18,fontSize:22,fontWeight:700,color:'#182f49'}}>{names[suite as keyof typeof names]}</div><div style={{position:'absolute',right:160,top:19,fontSize:19,color:'#526478'}}>{suite==='ContinuingSupport'?'Virtual clock / waiting shortened':suite==='CourseSetup'?'Synthetic accounts / real AI / waits shortened':'Synthetic accounts / real AI responses'}</div><div style={{position:'absolute',left:160,top:60,width:1600,height:900,overflow:'hidden',borderRadius:10,boxShadow:'0 4px 24px #182f4922',background:'white'}}><div style={{position:'absolute',width:1600,height:900,transformOrigin:'0 0',transform:`translate(${x}px,${y}px) scale(${z})`}}><OffthreadVideo src={staticFile(shot.file)} startFrom={Math.round(shot.start*FPS)} playbackRate={shot.rate} muted style={{width:1600,height:900}}/><Cursor click={shot.click} t={t}/></div></div><div style={{position:'absolute',left:0,right:0,bottom:0,height:108,background:'#182f49',color:'white',display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',padding:'12px 145px',fontSize:34,lineHeight:1.25,fontWeight:500}}>{shot.caption}</div></AbsoluteFill>}
function Demo({suite}:{suite:keyof typeof clips}){let f=0;return <AbsoluteFill>{clips[suite].map((s,i)=>{const from=f;f+=s.duration*FPS;return <Sequence key={i} from={from} durationInFrames={s.duration*FPS}><Shot shot={s} suite={suite}/></Sequence>})}</AbsoluteFill>}
registerRoot(()=> <>{Object.entries(clips).map(([suite,ss])=><Composition key={suite} id={suite} component={Demo} defaultProps={{suite}} durationInFrames={ss.reduce((n,s)=>n+s.duration,0)*FPS} fps={FPS} width={1920} height={1080}/>)}</>);
