"""Prepare the source-backed CTO narrative; retain previous deck builds."""
from pathlib import Path
import json,copy
R=Path(__file__).resolve().parents[1];B=R/'reports/generated/cto-slide-build';B.mkdir(parents=True,exist_ok=True)
old=json.loads((R/'reports/generated/slide-build/deck-content.json').read_text())['slides'];slides=[]
def add(title,kind,refs=(),**kw):
 sources=list(dict.fromkeys(p for n in refs for p in old[n-1].get('sources',[])))
 s=dict(title=title,kind=kind,number=len(slides)+1,notes='',sources=sources,foot='',**kw);slides.append(s);return s
def tbl(title,intro,rows,takeaway,refs,limit='',widths=(300,440,420)):
 return add(title,'readerTable',refs,intro=intro,rows=rows,widths=list(widths),takeaway=takeaway,limit=limit)
def fig(title,intro,name,takeaway,refs,foot=''):
 s=add(title,'focusFigure',refs,intro=intro,image='reports/presentation/diagrams/cto/'+name+'.png',takeaway=takeaway);s['foot']=foot;return s
def clone(n,**kw):
 s=copy.deepcopy(old[n-1]);s.update(kw,number=len(slides)+1,backup=False,notes='');s.pop('audited_number',None);slides.append(s);return s
add('Developing a Course Digital Twin','cover',[1],subtitle='Software for continuing student support\nDesign choices, tested improvements and the next iteration',details='Hikaru\nGraduate computer science presentation\n8 September 2026')
tbl('Presentation roadmap','What the software does, why these designs were retained, and what comes next.',[
 ['Chapter','Focus','Question'],['1 · Product','Purpose and demonstration','What did we build?'],['2 · Design','Structure, data and execution','How does it work?'],['3 · Answers','Failures and design comparisons','Why this answer path?'],['4 · Autonomous support','Action selection and learner state','Why these decisions?'],['5 · Continuing operation','Goals, authority and recovery','How is state kept correct?'],['6 · Development','Current best choices and next work','What should change next?']], 'The comparisons explain software decisions; they are not one combined benchmark.',[1],widths=(280,450,430))
# Give the roadmap a roomier custom layout instead of squeezing seven rows into a general table.
slides[-1]['kind']='roadmap'
fig('Who uses the course assistant?','The professor sets the course context. The student interacts with the assistant over time.','01-context','The assistant can initiate permitted support without a new student question.',[2,3,4], '“Course Digital Twin” names this configurable assistant; reproducing a professor’s teaching remains an evaluation goal.')
s=clone(5,title='Demo: course setup and 30 days of support');s['videoGuide']='2 professors · 2 courses · 4 synthetic students\nWatch course publication, separate student histories and automatic follow-ups.';s['foot']='4:06 · Actual app, virtual time, deterministic demo responses. Some setup is off-camera. This is not a learning-effectiveness test.'
tbl('What has been built—and what remains open','A prototype supports course publication, student dialogue, saved goals and later check-ins.',[
 ['Area','Choice supported so far','Remaining acceptance gap'],['Answers','Make required answer facts explicit','Quality on new questions'],['Support decisions','Keep an allowed baseline action','Useful personalized support'],['Goal completion','Use evidence for that goal’s concepts','Educational validity of the rule']], 'The project has working software and bounded evidence for specific design choices.',[10,14,23,29], '“Best” means within the tested alternatives and conditions. Component success is not whole-system qualification.')
tbl('Requirements and acceptance conditions','Three requirements connect the implementation to the evaluations.',[
 ['Requirement','Required behavior','How it is checked'],['R1 · Correct answers','Include required facts supported by the published course','Answer and citation comparisons'],['R2 · Appropriate support','Choose actions using goals and relevant learner evidence','Action and timing comparisons'],['R3 · Controlled operation','Respect authority and preserve consistent saved state','Scope, revocation and retry checks']], 'Instructor fidelity and real-student usefulness remain acceptance questions.',[2,6,29], 'R1–R3 are presentation labels. The same requirements return in the final status review.')
fig('Current local software structure','The API serves interactions; background work continues from saved activity and due opportunities.','02-containers','Shared durable state connects student interactions to later support.',[25,26], 'Logical local configuration. The database and deployment topology have not won a comparative scaling study.')
fig('Data relationships behind continuing support','Each conversation and goal belongs to a student and a published course version.','03-erd','Goal completion must select evidence for the right student, release and target concepts.',[23,25], 'Physical ER subset. Crow’s foot = many; circle = optional. Goal-to-assessment matching is an application rule, not a direct foreign key.')
slides[-1]['sources']+=['src/digital_twin/student/migrations.py','src/digital_twin/student/repository.py']
fig('Two entry points into the same saved system','A student request starts a response; due saved work can start support later.','12-execution','Both paths recheck authority before saving their effects.',[3,4,25,26], 'UML sequence overview. A worker acts only when goal, evidence, consent and schedule checks permit support.')
fig('Current factual-answer path','BM25 ranks words in the permitted course evidence. The answer path checks support and selects facts.','06-answer-path','Keep a simple, inspectable answer path while improving completeness.',[7,11,25], 'BM25 is a keyword-based ranking method. The retained path assembles approved facts deterministically; richer wording paths are experimental.')
clone(7,title='Finding the source does not complete the answer')
fig('Why the more complex answer paths failed','Three historical paths used the same course evidence; two shared the same overly broad check.','07-answer-alternatives','Checking all question wording rejected cases whose required answer facts were available.',[8,9], 'These are separate UML activities. The result concerns the tested answer paths, not the value of event sourcing in general.')
clone(10,title='Explicit answer facts improved the same 397 cases')
# Main slide 14 keeps quality gates and two bounded negative examples, rather than hiding them in backup.
tbl('The strongest local result is still below acceptance','Fresh comparison: 800 answerable cases and 200 refusal/clarification cases.',[
 ['Test','Observed result','Development decision'],['Fresh answer quality','BM25: 63.25%; hybrid: 62%\nRequired: 95%','Keep the simpler control; refine quality'],['Refuse or clarify','BM25: 96%; hybrid: 95%\nRequired: 98%','Neither path passes both gates'],['Added methods, separate studies','Better visual retrieval did not improve answers; wording repair kept a critical error','Do not promote on intermediate scores']], 'Current best comparison results do not establish an acceptable teaching product.',[11,12,22], 'Visual study: retrieval 18→28/30, grounded answers 20/30 in both arms. Wording error: a necessary condition became a guarantee.',widths=(265,470,425))
fig('Current support planner: retain an allowed fallback','The planner chooses an action; a separate generator writes the selected message.','08-guarded-planner','A proposal replaces the baseline only when the replacement conditions pass.',[13,14], 'A = deterministic event rule. Replacement requires a valid permitted proposal, analytic support and a predicted gain of at least 0.04.')
tbl('Why reject-only verification was not retained','The earlier designs changed action selection while keeping shared permission constraints.',[
 ['Design','What it adds','Problem exposed'],['Fixed rules A','Choose a baseline action','Limited flexibility, but a useful control'],['Model proposal + lookahead','Propose and score possible actions','More stages did not beat A on utility in that fold'],['Reject-only verifier','Reject the selected proposal','Can remove a usable action without replacing it'],['Guarded replacement H','Keep A unless a proposal qualifies','Retains an allowed fallback when a proposal fails']], 'Preserve a usable baseline instead of treating rejection as a better action.',[13,14,15], 'Utility, preferred-action agreement and action validity are different measures. An earlier label/validity interpretation was corrected.')
clone(15,title='Guarded replacement earned a bounded preference')
clone(21,title='The planner input can rise without a new answer')
tbl('Learner models: what they estimate and how we test it','These candidates use assessed answers. They are not integrated into the current delivery-count input.',[
 ['Method','Meaning','Input and output'],['Count baseline','A simple count-based estimate','Assessed history → knowledge estimate'],['BKT','Bayesian Knowledge Tracing','Correct / incorrect attempts → probability of knowing a concept'],['PFA','Performance Factors Analysis','Success / failure history → next-answer probability']], 'Knowledge estimation and predicting the next answer are separate evaluation tasks.',[16,18,19], 'MSE = mean squared error against simulated hidden knowledge. Brier = squared error of a next-answer probability. Lower is better for both.')
s=clone(19,title='The best estimator depends on the prediction task');s['intro']='240 synthetic learners per condition; constant contact timing. All three methods receive assessed answers.';s['charts'][0]['categories']=['Count','BKT','PFA'];s['charts'][0]['series'][0]['values']=[.084,.035,.052];s['charts'][1]['categories']=['Count','BKT','PFA'];s['charts'][1]['series'][0]['values']=[.259,.259,.249];s['charts'][0]['detail']='BKT–Count: −0.050; 95% CI [−0.053, −0.047].';s['charts'][1]['detail']='PFA–Count: −0.010; 95% CI [−0.013, −0.008].';s['takeaway']='BKT fits hidden knowledge better here; PFA improves next-answer prediction against Count.';s['foot']='MSE and Brier are defined on the previous slide. CI = confidence interval. Synthetic results; no product integration.\nThe BKT–Count next-answer difference is inconclusive. A stronger count baseline and a third simulator remain needed.'
s=clone(20,title='Contact timing trades message count against learning');s['takeaway']='Halving messages also reduced simulated mastery. Evaluate usefulness, not just fewer contacts.';s['foot']='Constant: every eligible check. Conditional: wait for a need signal. Value: require predicted benefit above a margin.\nBKT + value had the highest mean day-30 mastery among tested feasible pairs (0.328); it remains an unintegrated candidate.'
fig('A goal outlives a single background job','A message attempt and a completed learning objective are different state changes.','09-goal-states','Complete a goal only when its own target concepts satisfy the evidence rule.',[23,24,25], 'UML state machine. Per target: at least 2 correct assessments, no incorrect assessment, confidence ≥0.5. These are software thresholds.')
tbl('Target-specific evidence removed false completions','Failure case: correct cache-coherence answers also completed an unassessed virtual-memory goal.',[
 ['Matched comparison','Old completion rule','Target-scoped correction'],['Histories per version','72 synthetic histories','72 synthetic histories'],['Supported completions','14','15'],['Unsupported completions','12','0']], 'Retain the scope correction. More follow-ups did not establish better learning.',[23,24], 'Same student and release are not enough: evidence must match each goal’s concepts. In the autonomous slice: 56 extra messages; mastery change −0.0024.')
fig('Authority can change while an answer is generated','The professor withdraws a release after generation starts but before the response is saved.','10-authority-change','Recheck current authority at commit; reject stale work before saving its effects.',[25], 'Generation runs outside the write transaction. Saved learner-state revisions are also checked to prevent stale updates.')
fig('A retry reuses the message already saved','The worker can stop after saving a message but before marking the job complete.','11-retry','A stable delivery key prevents a second in-app message during this retry.',[26], 'UML sequence: step 3 occurs after a crash and restart. This local contract does not guarantee exactly-once effects in external systems.')
clone(27,title='The integrated trial exposed weak continuing support')
tbl('Acceptance status against the original requirements','Working components do not yet satisfy all three product requirements.',[
 ['Requirement','Evidence available','Remaining gap'],['R1 · Correct answers','Explicit facts improved development cases','Fresh answers still miss quality gates'],['R2 · Appropriate support','Guarded planning and learner simulations','Proxy input; generic or discontinued support'],['R3 · Controlled operation','Scoped completion, authority and retry checks','Full retained configuration needs further integrated evaluation']], 'Instructor fidelity and real-student learning remain unestablished.',[11,15,23,25,26,27,28,29], 'Only valid, corrected evidence informs these conclusions. A protocol-invalid architecture comparison was excluded from selection.')
tbl('Current best choices—and their scope','Retain tested improvements; distinguish current software from promising standalone candidates.',[
 ['Area','Choice to retain or investigate','Scope of the evidence'],['Answers','Explicit required facts; simple retrieval control','Improvement, but acceptance gates fail'],['Support planner','Guarded replacement with baseline A','Small synthetic utility gain'],['Learner state','BKT / PFA depend on prediction target','Promising; not integrated'],['Persistent operation','Target-scoped completion and guarded saves','Bounded state and recovery checks']], 'There is no single fully qualified “best system” assembled from these separate studies.',[10,11,15,19,23,25,26], 'Current topology is a design choice, not a measured scaling winner. Each experimental result is tied to its own inputs and configuration.')
tbl('Next change: replace the planner’s proxy input','Test whether relevant assessed evidence produces better support decisions than delivery counts.',[
 ['Comparison element','Proposed next experiment'],['Control → candidate','Delivery-count input → committed target-concept evidence'],['Hold fixed','Planner, allowed actions, retrieval and wording'],['First compare','Identical snapshots: relevant, missing, unrelated and conflicting evidence'],['Then compare histories','Useful and missed support; inappropriate contact; authority; latency and cost']], 'Set decision thresholds before execution. Assess the evidence quality as well as the planner.',[21,30], 'Proposed work, not a completed result. Retain the control for comparison; do not silently replace the selected configuration.',widths=(310,850))
tbl('Continuing development: evidence determines the next step','Keep current controls while improving the parts that limit useful course support.',[
 ['Next development','Evidence needed to proceed'],['Improve answer completeness','Fresh independent cases meet factual and citation criteria'],['Repair learner-state input','Matched comparisons improve support without violating constraints'],['Integrate retained candidates','Repeat complete histories, permission changes and failure recovery'],['Evaluate in an approved course','Assess professor fidelity and student usefulness with appropriate consent']], 'Discussion: which acceptance gap should determine the next development priority?',[29,30,31], 'Answer quality and state-input work can proceed separately; their accepted changes must be evaluated together before broader use.',widths=(400,760))
# Reading review: define terms before results and separate the two negative studies.
slides[2]['intro']='The professor publishes materials and teaching policy; students ask questions and receive later support.'
slides[3]['videoGuide']='Watch publication, separate student histories and automatic follow-ups.'
slides[3]['foot']='4:06 · 2 professors, 2 courses, 4 synthetic students · Actual app with virtual time and deterministic responses.\nSome setup is off-camera. The recording demonstrates operation, not learning effectiveness.'
slides[7]['intro']='A release fixes course materials and settings. Conversations and goals refer to that published version.'
slides[13]['title']='Fresh answers still missed the acceptance thresholds'
slides[13]['rows']=slides[13]['rows'][:3]
slides[13]['limit']='BM25 ranks keyword matches. Hybrid adds semantic retrieval. Both use the same answer check. Grounded means complete and source-supported.'
slides[15]['rows'][2][2]='More stages did not beat A on the earlier evaluation score'
slides[15]['limit']='The next comparison separates action validity from evaluation utility: the simulated value of the chosen action.'
slides[16]['title']='Guarded replacement slightly improved simulated utility'
slides[17]['limit']='This is current input-adapter behavior. The next slides test assessed-answer alternatives. Goal completion uses assessed evidence separately.'
slides[19]['intro']='240 synthetic learners per condition, two simulator families, 30 days. Constant contact timing is held fixed.'
slides[20]['title']='Contact timing changes messages and simulated knowledge'
slides[21]['foot']='Per target: ≥2 correct, no incorrect, confidence ≥0.5. Confidence = min(0.95, n/(n+2)), n = assessed attempts.\nThese are software completion thresholds, not validated mastery criteria.'
negative=dict(number=15,kind='explanation',notes='',sources=list(dict.fromkeys(old[11]['sources']+old[21]['sources'])),foot='',
 title='Better retrieval or wording did not ensure correct answers',
 intro='Two separate studies tested improvements around the answer path. Neither qualified the final output.',
 items=[['Visual retrieval','Relevant evidence: 18 → 28 / 30\nGrounded answers: 20 / 30 in both\nFinding more relevant images did not improve complete, supported answers.'],
 ['Wording revision','Source: “Exactly two seals are required.”\nRevision: “Two seals guarantee acceptance.”\nThe revision changes a requirement into a guarantee.']],
 takeaway='Evaluate the final answer, not only evidence retrieval or fluent wording.',
 limit='Separate datasets. Wording candidates each repaired 47/56 defective drafts and preserved 56/56 adequate drafts, but a critical error remained.')
slides.insert(14,negative)
assert len(slides)==31
for n,s in enumerate(slides,1):
 s['number']=n;s['chapter']=next(t for a,b,t in [(1,5,'1 · Product'),(6,9,'2 · System design'),(10,15,'3 · Answer design'),(16,22,'4 · Autonomous support'),(23,26,'5 · Continuing operation'),(27,31,'6 · Continuing development')] if a<=n<=b)
 s['sources']=list(dict.fromkeys(s['sources']))
 for p in s['sources']:assert (R/p).exists(),p
 for key in ['backup','audited_number','old_number','gloss','termNote']:s.pop(key,None)
(B/'deck-content.json').write_text(json.dumps({'slides':slides,'main_slide_count':31},indent=2))
print('Prepared 31 slides with chapters and sources; no appendix.')
