"""Prepare evidence-linked English deck content and a separate speaking script."""
from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'reports/generated/slide-build';OUT.mkdir(parents=True,exist_ok=True)
old={}
for n,title,part in re.findall(r'### (\d+)\. ([^\n]+)\n(.*?)(?=\n### |\Z)',(ROOT/'reports/presentation/speaker-script.md').read_text(),re.S):
 m=re.search(r'\*\*English script\*\*\s*(.*?)(?=\n\*\*操作|\Z)',part,re.S)
 if m:old[int(n)]=m[1].strip()
E='research/05_evaluation/'
sources={
 'brief':'research/06_reports/final/chapters/01-objective.tex',
 'workflow':'research/06_reports/final/chapters/02-course-workflow.tex',
 'runtime':'research/06_reports/final/chapters/03-runtime-design.tex',
 'comparisons':'research/06_reports/final/chapters/04-comparisons.tex',
 'profiles':'research/06_reports/final/chapters/profile-examples.tex',
 'round1':E+'course-digital-twin-whole-system-architecture-round-1-001-results.md',
 'A':E+'course-digital-twin-whole-system-architecture-round-2-001-results.md',
 'B':E+'final-cross-method-factual-confirmation-001-results.md',
 'C':E+'successor-architecture-confirmation-005-001-results.md',
 'D':E+'successor-architecture-engine-comparison-006-001-results.md',
 'E':E+'successor-learner-timing-simulation-001-results.md',
 'F':E+'independent-factual-revision-controls-001-fresh-v16-live-001-results.md',
 'G':E+'final-profile-operational-dialogue-development-001-full-live-001-results.md',
 'H':E+'goal-completion-scope-development-001-results.md',
 'fold3':E+'successor-architecture-development-fold-003-single-case-001-results.md',
 'audit3':E+'successor-architecture-fold-003-causal-audit-001-results.md',
 'fold4':E+'successor-architecture-policy-value-fold-004-001-results.md',
 'correction':E+'course-digital-twin-whole-system-architecture-round-3-001-analysis-correction-001-results.md',
 'L1':E+'factual-qa-v3-scale-completion-10000-001-analysis-correction-001-results.md',
 'L3':E+'academic-factual-qa-open-10000-winner-regression-001-results.md',
 'demo':'reports/presentation/recording/live-virtual-demo.md',
 'designs':'reports/presentation/design-comparisons.md',
}
slides=[]
def add(title,kind='table',*,notes='',oldnote=None,refs=(),foot='',**kw):
 slides.append(dict(title=title,kind=kind,notes=old.get(oldnote,notes) if oldnote else notes,
                    sources=[sources[r] for r in refs],foot=foot,**kw))
def fig(name,standard=True):return 'reports/presentation/diagrams/'+('standard/' if standard else 'failures/')+name+'.png'
add('An Instructor-Configurable\nCourse Digital Twin','cover',oldnote=1,refs=['brief'],
 subtitle='Software design, experimental findings and remaining limitations',details='Hikaru\nResearch project presentation\n7 September 2026')
add('Delivery against the project brief',oldnote=2,refs=['brief','workflow','G','H'],foot='Implementation and verification have different acceptance scopes.',
 rows=[['Requested outcome','Implemented','Remaining acceptance gap'],['Course configuration','Reviewed materials and releases','Bounded local workflow only'],['Grounded support','Course scope and source citations','Fresh factual gates remain unmet'],['Teaching preferences','Approved profile enters generation','Actual-instructor fidelity untested'],['Continuing support','Persistent goals and scheduled work','Useful intervention unestablished'],['Instructor oversight','Review, pause and withdrawal','Full current composition needs evaluation']],widths=[270,430,460])
add('Thirty virtual days in the actual software','video',refs=['demo'],foot='Recording configuration: deterministic baseline. Synthetic users and time. Duration 4:06.',
 image='reports/generated/autonomous-film/review-18.png',
 notes='I will first show the software. There are two professors, two courses and four synthetic students. Watch what happens after a student stops typing. The system observes the saved state and processes due work as the virtual clock advances. Also watch the professor pause and the student consent change. The recording uses existing deterministic services in an isolated environment. It is a demonstration of operation, not the historical model-backed evaluation.\n\n[Play the embedded video. No speech for 4 minutes 6 seconds.]\n\nThe important point is that support can originate from the system. The remaining slides examine whether the designs behind that behavior are useful, correct and supported by valid evidence.')
add('Instructor settings and observed behavior','settings',refs=['workflow','profiles'],foot='Saved finding F21. This is a historical example, separate from the new demo.',
 rows=[['Setting','Where it acts'],['Approved sources and objectives','Evidence selection and goal scope'],['Action permissions and consent','Execution and delivery checks'],['Tone, depth and help sequence','Inputs to response generation']],
 quote='For “How does slot seal work”, what is your current explanation, and which step are you unsure about?',
 points=['The response elicits an attempt.','Concept-specific diagnosis remains absent.'],
 notes='The instructor settings reach different parts of the software. Source permissions define what evidence the tutor may use. Approved objectives define what its goals may cover. Action permissions and consent restrict whether the system can deliver a proposed action. These are executable controls. A response model cannot authorize itself to ignore them.\n\nTeaching preferences have a different role. Tone, explanation depth and the help sequence enter the generation pathway. Their presence in an input does not prove that the output follows the instructor’s practice. We need to inspect what the student actually receives.\n\nThis saved Socratic profile requested a diagnostic question, a student attempt and then one hint. The student asked how slot seal worked in the synthetic course protocol. The tutor asked for the student’s current explanation and the step they were unsure about. That shows part of the intended help sequence. However, it does not diagnose the particular conceptual difficulty. The response is still generic.\n\nA separate explanatory example uses a different topic and context. It is not a controlled profile comparison. For a stronger test, I would hold the question, evidence and learner state fixed, vary only the approved profile, and independently review the resulting instruction. That remains proposed work. The owner can inspect the settings and enforcement points now, but instructor fidelity still needs evidence.')
add('System architecture and comparison boundaries','figure',oldnote=6,refs=['runtime'],image=fig('02-c4-containers'),foot='Logical container view. The demo uses a local harness for worker ticks and synchronous ingestion.')
add('What the simulation executes and supplies','figure',refs=['G','E','demo'],image=fig('14-operational-components',False),foot='Study G executes software and model calls. Study E separately evaluates latent learner state and timing.',
 notes='There are three different kinds of evidence in this presentation, and I do not want to combine their claims. The video shows a new deterministic software demonstration. Its student inputs and thirty-day clock are controlled, while existing product services create goals, select actions and save deliveries.\n\nThe historical operational dialogue study shown in this component diagram also supplies synthetic student behavior and virtual elapsed time. However, it invokes the configured external model through actual tutoring and autonomy services. It checks saved turns, delivery, consent and restart behavior. The student driver decides attendance and constructs replies according to its configured probabilities. Those replies are not observations from real students.\n\nThe learner and timing study is separate. It contains a hidden simulated learner state for scoring predictions and intervention outcomes. It does not execute the text retrieval and generation pipeline. The candidates see permitted observations, while the evaluator can use hidden simulator state. That distinction is why a lower estimation error there does not demonstrate better instructional text in the product.\n\nIn a classroom, actual students would supply attendance, attempts and reactions. Here those inputs are simulated so that runs are finite and reproducible. The measured software actions are real executions, but the human behavior and educational outcome assumptions are supplied by the experimental design. I therefore attach each result to its own study rather than calling every thirty-day result the same experiment.')
add('Why the first factual designs rejected questions',oldnote=7,refs=['round1'],foot='Round 1: 495 development cases, 350 chunks, no external model. Boundary action 100% in all arms.',
 rows=[['Design tried','Added mechanism','Grounded','Answerable action'],['Lexical control','Any-hit acceptance','52.66%','100%'],['Evidence-first hierarchy','Whole-question coverage','24.81%','36.46%'],['Plan-observe manifest','Decomposition and observations','24.81%','36.20%']],widths=[315,395,200,250],
 points=['Both complex paths shared the same downstream coverage defect.','Question scaffolding became a requirement for evidence.'])
add('Typed targets helped; extra ranking did not',oldnote=8,refs=['A'],foot='Study A: one development fold, 397 answerable cases within 497 total cases.',
 rows=[['Candidate','Grounded answerable cases','p95 latency'],['Control before typed targets','253 / 397','—'],['Typed target and cardinality','355 / 397','1.36 ms'],['Typed target plus section ranking','355 / 397','2.79 ms']],widths=[560,350,250],
 points=['Making the required facts explicit improved this development result.','The extra ranking stage added latency without a quality gain.'])
add('Retrieval did not ensure complete answers',oldnote=9,refs=['B'],foot='Study B: fresh, source-disjoint 1,000 cases. Grounded gate 95%; boundary gate 98%.',
 rows=[['Actual-product arm','All evidence@3','Fully grounded','Boundary action'],['BM25 + dominance gate','98.00%','63.25%','96.00%'],['Qwen3 hybrid + same gate','92.88%','62.00%','95.00%']],widths=[490,215,220,235],
 points=['The retained fallback still missed the acceptance gates.','A correct region can still yield the wrong claim or an incomplete answer.'])
add('Planner alternatives and the reject-only failure',refs=['fold3','audit3','fold4'],foot='Fold 003 labels were later reinterpreted. Preferred-label agreement was not action validity.',
 rows=[['Design','Action-selection mechanism','Finding'],['A','Deterministic event rule','Retained as the control'],['B','Model proposal without lookahead','Did not justify replacing A'],['C','Proposal plus analytic lookahead','Mixed label and utility results'],['C + V','C followed by a rejecting verifier','Rejection supplies no replacement']],widths=[150,545,465],
 points=['A verifier could suppress an otherwise usable selected action.'],
 notes='The planner comparison changed the decision stages inside a common execution boundary. Every method still faced the same permissions, evidence checks and delivery rules. A used a deterministic event rule. B asked a model to propose a permitted action without lookahead. C added deterministic analytic lookahead to rank actions. C plus V added a model verifier after the C selection.\n\nThe question was whether these extra decision stages improved the resulting action enough to justify replacing the simple control. In the third development fold, the deterministic control had the best registered hidden utility. B’s direct proposal did not justify automatic priority over that control. C had stronger agreement with a preferred-action label, but lower utility than A. Those metrics asked different questions.\n\nThe additional verifier exposed a more concrete failure. It could reject a usable move, and the reject branch returned no action. It did not search for another useful move or return the baseline. This is a failure of the reject-only composition, not an argument that all verification is harmful.\n\nThe later audit also corrected the interpretation of acceptable-move scores. Preferred-label agreement had been confused with permitted transition validity. Five planner failures came from a non-authoritative reason-string length constraint. These details matter because they explain which boundary failed. They do not support saying that the entire safety mechanism collapsed. The successor therefore preserved the baseline when a proposed replacement did not earn acceptance.')
add('Guarded replacement retains the baseline','figure',refs=['fold4','C'],image=fig('11-guarded-replacement',False),foot='Study C, 1,000 contexts: A/H utility 0.7954/0.8002; preferred label 74%/73%; valid action 100%/100%.',
 notes='The H design changes what happens when a proposal is weak. It first computes the deterministic baseline. If there is no authorized evidence, the result is no action. When evidence is available, a model proposal can replace the baseline only if it is valid, permitted, agrees with the analytic best action and exceeds the minimum value margin of zero point zero four. Otherwise, the method keeps A.\n\nThis preserves a useful available move instead of allowing a reject-only stage to remove it without replacement. In the fresh fourth fold, all four methods produced valid actions. H had utility zero point seven eight eight zero compared with zero point seven eight six zero for A. The other methods did not dominate all metrics.\n\nIn the separate one-thousand-context confirmation, H again had a small positive paired utility improvement. The means were zero point eight zero zero two for H and zero point seven nine five four for A. Preferred-label agreement fell from seventy-four to seventy-three percent. The result supports conditional progression, not improvement on every measure.\n\nThere is still an important unresolved question. The analytic ranking, fallback and model proposal work together. This comparison does not isolate the value added by the language model itself. An analytic-only ablation would be needed. Also, this utility comes from a synthetic instrument and must not be presented as a measured gain in student learning. The default learner proxy remains another limitation in the inputs to this design.')
add('Learner estimation and delivery timing',oldnote=15,refs=['E'],foot='Study E: 240 simulated learners per condition, 30 virtual days. Full grid in backup.',
 rows=[['Estimator + timing','MSE','Messages','Waste','Simulated mastery'],['Count + constant','0.084','14.0','50.6%','0.314'],['Count + conditional','0.084','7.0','38.8%','0.302'],['Count + value','0.084','10.2','34.1%','0.317'],['BKT + value','0.037','12.3','30.1%','0.328']],widths=[410,150,170,170,260],
 points=['Fewer messages can also remove useful practice.','BKT/value remains a hypothesis for further evaluation.'])
add('The default planner still receives a delivery proxy','figure',oldnote=16,refs=['runtime','designs'],image=fig('12-delivery-proxy',False),foot='Current adapter behavior. Experimental BKT results do not establish product integration.')
add('Structured wording retained critical semantic errors','wording',oldnote=17,refs=['F','comparisons'],foot='Study F: 56 adequate/defective pairs per revision candidate. AI-assisted review; no student outcome measure.',
 rows=[['Revision result','Each candidate'],['Adequate drafts preserved','56 / 56'],['Defective drafts repaired','47 / 56'],['Critical errors remaining','1']],
 points=['Source: exactly two seals are required.','Output defect: an added example guarantees acceptance with two seals.','A necessary condition became a sufficient condition.'],
 decision='Both candidates failed the zero-critical-error gate.')
add('Completion used evidence from the wrong objective','figure',oldnote=18,refs=['H','runtime'],image=fig('13-completion-scope',False),foot='A scope defect: evidence about topic A could complete a goal about topic B.')
add('The correction fixed completion scope',oldnote=19,refs=['H'],foot='Study H: 72 histories per arm; secondary autonomous slice has 36 per arm. Synthetic 30-day histories.',
 rows=[['Completed-goal audit','Control','Corrected'],['Supported completions','14','15'],['Unsupported completions','12','0'],['Total completed goals','26','15']],widths=[600,280,280],
 points=['The autonomous slice delivered 56 additional messages.','Mean final simulated mastery changed by −0.0024.','Keep the correctness fix; learning improvement remains unestablished.'])
add('Authority is checked when saving a turn','figure',refs=['runtime'],image=fig('06-uml-tutoring-sequence'),foot='Local authority and revision contracts. No claim of a deployment-topology benchmark.',
 notes='Some retained boundaries were requirements-driven choices rather than winning experimental architectures. A published release fixes approved source versions and configuration. Current authority can still change while the system prepares a response.\n\nThe application performs generation outside the transaction, then checks authority again at commit. If the release has been withdrawn or permission has been revoked, the earlier successful check cannot authorize the later effect. The saved turn must still belong to the allowed course and release.\n\nAn accepted turn saves the response, its citations and the learner update together. A revision check prevents a result based on stale learner state from silently overwriting a newer state. The important point on the sequence diagram is the boundary between preparing a candidate response and committing an authorized turn.\n\nThese checks address concrete consistency and permission requirements. They do not prove that SQLite or the chosen process topology outperforms a distributed alternative. I have not performed that deployment comparison. The evidence supports the specific local contract that a prepared answer must pass the current checks before its effects become committed state. The next slide addresses a separate problem: how to recognize an effect that was already saved before a worker stopped.')
add('A retry recognizes the saved in-app delivery','figure',refs=['runtime'],image=fig('08-uml-recovery-sequence'),foot='Local in-app recovery. External provider effects do not have a global exactly-once guarantee.',
 notes='For proactive support, the message save and job-result save are separate steps. Imagine that the worker saves the message successfully and then stops before recording the completed job result. When its lease expires, another worker can claim the work. A lease alone does not tell that worker whether the student-facing effect already exists.\n\nThe stable delivery identity is the additional mechanism. Recovery uses the same key and recognizes the message that was already saved. It can finish the job bookkeeping without sending another in-app message. A matching request identifier provides a related reuse contract for ordinary tutoring turns.\n\nThe authority check still matters during recovery. A stable key does not create permission to send new content, and a lease does not replace the saved-effect check. These mechanisms solve different parts of the failure.\n\nThis is a local persistence guarantee for the tested path. It is not a promise of exactly-once effects across every external provider. If a provider outcome is uncertain, the system must not blindly repeat an irreversible effect. The retained tests exercise these boundaries, but they are not a benchmark of alternative production topologies. Keeping that distinction makes the architecture claim precise and reviewable.')
add('The integrated trial ran, but support stayed generic',oldnote=21,refs=['G'],foot='Historical Study G, separate from the new demo. 24 histories over 30 virtual days.',
 rows=[['Observed operation','Result'],['Tutor turns','484'],['External model calls','654; 11 reached the output limit'],['Proactive messages / synthetic replies','16 / 10'],['Service restarts / consent changes','24 / 48'],['Tutor turns ending in safe graph failure','13']],widths=[560,600],
 points=['All 16 check-ins quoted a source card with a generic wrapper.','Operational completion did not establish useful personalized teaching.'])
add('Evaluation corrections limit the surviving claims',oldnote=22,refs=['L1','L3','correction','audit3'],foot='Preserve invalid runs and their corrections. Do not rank their raw scores as valid selection evidence.',
 rows=[['Problem','Claim withdrawn or narrowed'],['Reference answer visible during authoring','10,000-case result is not independent product quality'],['Unresolved aggregate contradiction','Exclude the unsupported grounded percentage'],['Round 3 exceeded the candidate limit','Retain diagnostics, invalidate preregistered selection'],['Preferred labels confused with validity','Separate agreement, valid action and utility']],widths=[495,665],
 points=['Valid evidence remains for specific typed-target, factual, planner and lifecycle comparisons.'])
add('Next comparison: the planner-input adapter',refs=['runtime','H'],foot='Proposed experiment. No result or acceptance threshold has been claimed.',
 rows=[['Comparison element','Proposed design'],['Control','Current delivery and event proxy'],['Candidate','Committed evidence for the goal’s target concepts'],['Held fixed','Planner, allowed actions, retrieval and wording'],['First evaluation','Identical saved snapshots, including missing and unrelated evidence'],['Then complete histories','Useful/missed support, constraints, latency and cost']],widths=[330,830],
 notes='The next experiment would change one specific boundary: the adapter that prepares the planner input. The control would keep the delivery and event proxy. The candidate would use committed assessment evidence for the target concepts of the goal. The planner, permitted actions, retrieval and wording would initially stay fixed.\n\nMy hypothesis is that distinguishing correct, incorrect and missing evidence will make the decision respond more directly to the student’s observed difficulty. That is a proposal, not an established result. It does not require assuming that a larger model will solve the problem.\n\nI would first compare decisions on identical saved snapshots. The cases should include unrelated concepts, conflicting evidence, ambiguous assessment and missing observations. The dataset, scoring rules and acceptance thresholds must be fixed before the run. Then I would compare complete histories, where different actions can legitimately produce different later replies.\n\nThe measurements should cover inappropriate interventions, useful interventions, missed support, the existing authority and lifecycle constraints, and operational cost. We also need an independent check that the assessment evidence itself is meaningful. An improved adapter cannot compensate for an incorrect assessment.\n\nThis comparison can proceed on fixed, reviewed inputs while factual and instructional quality remain acceptance priorities. Before making a broader product claim, the selected components need to be frozen and evaluated together. A later approved course pilot would be needed to examine actual usefulness and student experience. That dependence is why I do not present this single adapter change as the completion of the whole project.')
add('Deliverable, findings and acceptance gaps','closing',refs=['brief','comparisons','H'],
 sections=[['Delivered','A working prototype for course configuration, grounded tutoring and governed continuing support.'],['Defensible findings','Explicit evidence contracts helped. Reject-only verification lost usable moves. Exact objective scope fixed invalid completion.'],['Still unresolved','Factual acceptance, instructor fidelity and useful intervention in a real course.']],
 notes='The deliverable is a working research prototype with inspectable decisions and persistent support. The video showed the software operating across multiple synthetic users and thirty virtual days. The studies explain why I retained some components and did not promote others.\n\nThe strongest engineering findings concern specific boundaries. Typed targets improved a development evidence contract. A reject-only verifier could lose an available useful move. Guarded replacement preserved the control. Exact objective scope removed unsupported completion in the matched study.\n\nThose findings do not add up to proven teaching effectiveness. Factual acceptance, instructor fidelity and the usefulness of intervention remain incomplete. The next comparisons must address those gaps while keeping the current control and making failure visible.\n\nI would therefore describe the project as an implemented and evaluated research prototype with bounded engineering findings. It is ready for a focused discussion of the next acceptance decision, rather than a claim that autonomous teaching quality has already been solved.')
add('Questions','questions',notes='Use the backup diagrams and the defence notes for detailed questions.',sections=[['Discussion','Design choices, failure mechanisms, evaluation scope and next steps.']])
for title,image,refs in [
 ('System context',fig('01-c4-context'),['runtime']),('Course publication workflow',fig('03-uml-course-activity'),['workflow']),
 ('Domain model and persistence',fig('04-uml-domain-classes'),['runtime']),('Publication and approval sequence',fig('05-uml-publication-sequence'),['workflow']),
 ('Goal lifecycle',fig('07-uml-goal-state-machine'),['runtime','H']),('Historical factual paths',fig('09-factual-designs',False),['round1']),
 ('Reject-only verification path',fig('10-reject-only',False),['fold3','audit3'])]:
 add(title,'figure',image=image,refs=refs,foot='Backup diagram. Scope and notation are stated inside the figure.',notes='Backup. Explain only the part relevant to the question. Preserve the scope stated in the figure.')
add('Full estimator and timing comparison',refs=['E'],foot='Backup. 240 simulated learners per condition. All mastery values are hidden simulator states.',
 rows=[['Estimator + timing','MSE','Messages','Waste','Mastery'],['Count + constant','.084','14.0','50.6%','.314'],['Count + conditional','.084','7.0','38.8%','.302'],['Count + value','.084','10.2','34.1%','.317'],['BKT + constant','.035','14.0','46.4%','.317'],['BKT + conditional','.035','8.9','36.6%','.309'],['BKT + value','.037','12.3','30.1%','.328'],['PFA + constant','.052','14.0','50.8%','.313'],['PFA + conditional','.051','7.3','41.5%','.303'],['PFA + value','.051','10.5','34.7%','.313'],['Count + oracle (bound)','.086','12.2','0.0%','.345'],['Count + never (bound)','.083','0.0','—','.288']],widths=[430,160,170,170,230],compact=True,oldnote=15)
add('Planner confirmation and model allocation',refs=['fold4','C','D'],foot='Backup. Each table is a separate study. Do not subtract values across folds.',
 rows=[['Study / comparison','Result','Interpretation'],['Fold 004: A / B / C / H utility','.7860 / .7564 / .7807 / .7880','All valid 100%'],['Study C: A / H utility','.7954 / .8002','Preferred agreement 74% / 73%'],['Study D: Luna / Terra planner','.7935 / .7938','Alternative effect interval includes zero'],['Study D: Luna / Mini wording','Final valid wording 100%','Includes fallback'],['Terra planner + Luna wording','238 / 240 generator calls completed','Missed 99.5% completion gate']],widths=[435,350,375],oldnote=14)
add('Visual retrieval and grounded answers',refs=['comparisons'],foot='Backup. Two separate 30-case comparisons. Both controls retained citation limitations.',
 rows=[['Comparison','Control','Visual candidate','Decision'],['Historical relevant visual retrieval','18 / 30','28 / 30','Retrieval improved'],['Same study: grounded answers','20 / 30','20 / 30','No end-to-end gain'],['Fresh omni study: grounded answers','26 / 30','16 / 30','Drop candidate']],widths=[490,190,225,255],
 points=['Source-region lineage and packet layout remained failure surfaces.'],notes='The historical visual and fresh omni studies use different inputs. Do not combine their numbers into a trend. General scanned-PDF OCR remains unqualified in the stated report scope.')
add('Evidence index: studies and decisions',refs=['A','B','C','D','E','F','G','H'],foot='Full repository paths and citations are in each slide’s speaker notes.',
 rows=[['Study','Scope','Bounded decision'],['A','Typed targets on development cases','Retain contract change; refine'],['B','Fresh factual confirmation','Fallback retained; quality gates unmet'],['C / D','Guarded planning and model allocation','Conditional progression'],['E','Learner estimation and timing','Go Deeper; no product BKT integration'],['F','Bounded wording revision','Do not promote'],['G','Historical 30-day operation','Operation exercised; teaching remains weak'],['H','Objective-scoped completion','Keep correctness correction']],widths=[140,555,465],compact=True,
 notes='Source paths:\n'+'\n'.join(f'{k}: {sources[k]}' for k in 'ABCDEFGH'))
add('Evidence index: corrections and demonstration',refs=['round1','fold3','audit3','fold4','correction','L1','L3','demo'],foot='The new recording and historical evaluations have separate configurations and claims.',
 rows=[['Material','How it is used'],['Round 1 / Fold 003 / Fold 004','Design history with their original scopes'],['Fold 003 causal audit','Correct interpretation of action metrics'],['Round 3 correction','Invalid selection; disclosed diagnostics only'],['10,000-case analysis correction','Withdraw independent product-quality claim'],['Winner-regression record','Exclude unresolved aggregate claim'],['New 30-day screen recording','Actual software demo using deterministic services']],widths=[500,660],compact=True,
 notes='Read the linked correction alongside the original result. The new screen recording is not evidence that the historical external-model composition was requalified. No real-student learning claim is made.')
for i,s in enumerate(slides,1):
 s['number']=i;s['backup']=i>23
 for source in s['sources']:assert (ROOT/source).exists(),source
 if 'image' in s: assert (ROOT/s['image']).exists(),s['image']
word_count=sum(len(re.findall(r"\b[\w’'-]+\b",s['notes'])) for s in slides[:22])
(OUT/'deck-content.json').write_text(json.dumps({'slides':slides,'main_word_count':word_count,'font':'Arial','main_slides':22},indent=2))
script=['# English presentation script','',f'22 main slides, a 4:06 video, Questions, and {len(slides)-23} backup slides.','',f'Spoken main-note text: approximately {word_count} words. The playback instruction is not spoken.','',f'At 150 words/min: approximately {word_count/150+4.1:.1f} minutes plus slide transitions. At 160: {word_count/160+4.1:.1f} minutes. Rehearse before relying on these estimates.','']
for s in slides:
 script += [f'## {s["number"]:02d}. {s["title"].replace(chr(10)," ")}', '',s['notes'],'','Sources: '+', '.join(s['sources']),'']
(ROOT/'reports/presentation/speaker-script-final.md').write_text('\n'.join(script))
print(len(slides),'slides;',word_count,'main-note words')
