"""Make the research deck understandable without its spoken narration."""
import json,re
from pathlib import Path
from copy import deepcopy
P=Path('reports/generated/slide-build/deck-content.json')
d=json.loads(P.read_text());old={s['number']:deepcopy(s) for s in d['slides']}
def gloss(n,*lines):old[n]['gloss']=list(lines)
def edit(n,**changes):old[n].update(changes)
gloss(2,'Digital twin here = a course tutor configured by an instructor; fidelity to a real instructor is untested.','Grounded = supported by approved course evidence. An acceptance gate is a required pass threshold.')
gloss(4,'Profile = approved teaching settings. Elicitation asks for a student attempt; diagnosis identifies its specific error.')
gloss(5,'Release = a published version of sources and settings. Worker = a process that handles queued or scheduled work.','C4 = Context, Containers, Components, Code. This view shows applications and stores, not a network deployment.')
gloss(6,'A simulated driver supplies student inputs. A virtual clock advances elapsed time without waiting real days.')
gloss(7,'Grounded = all required claims supported. Answerable action = answer given when the case has sufficient evidence.','Coverage defect: words that frame the question were incorrectly treated as facts that sources must contain.')
gloss(8,'Typed target = an explicit required fact or set; cardinality = the required number of items.','p95 latency = 95% of measured requests finished within this time. Lower is faster.')
gloss(9,'BM25 = keyword-based ranking; Qwen3 hybrid adds semantic retrieval. The gate filters acceptable evidence.','All evidence@3 = every required fact retrieved in the top 3; grounded = complete, supported answer.','Boundary action = correct refusal/clarification when required. Source-disjoint = test sources differ from development.')
gloss(10,'Planner = chooses the next action. Lookahead estimates its consequences; the verifier accepts or rejects it.','A/B/C/C+V are local design labels, not standard algorithm names. V denotes the added verifier.')
gloss(11,'H = guarded replacement. Utility = study-specific simulated action value, not measured learning gain.','Preferred = matches the reference action; valid = obeys the permitted action/transition rules. Higher utility is better.')
gloss(12,'MSE = mean squared error against hidden simulator mastery (lower is better); messages = mean per learner.','Waste = sent while mastery ≥ 0.85 or the learner is unreceptive. Mastery = hidden day-30 simulator state.')
gloss(13,'Proxy = an indirect substitute. Here the count measures delivered actions, not correct student answers.')
gloss(14,'Adequate/defective = initially acceptable/flawed drafts. Critical = a serious change to the source’s meaning.')
gloss(15,'Objective = the goal being pursued; target concept = the specific subject whose assessed evidence may satisfy it.')
gloss(16,'Supported = meets the target-concept completion rule. A history = one simulated learner’s 30-day interaction.','Autonomous slice = histories where the system may initiate support; it is a subset of the full audit.')
gloss(17,'Commit = save accepted effects. Revision = state version; a mismatch means the generated result may be stale.')
gloss(18,'Stable key = the same identifier across retries. Lease = temporary worker ownership; neither grants permission.')
gloss(19,'Safe graph failure = the tutor workflow stopped safely instead of completing a response.','A synthetic reply is produced by the simulation; it is not evidence that a real student found the message useful.')
gloss(20,'Independent = answers were not visible during authoring. Diagnostic results help explain faults, not select a winner.')
gloss(21,'Adapter = code translating saved state into planner input. Hold other components fixed to isolate its effect.')
gloss(22,'Acceptance gap = a project requirement for which sufficient evidence has not yet been demonstrated.')
gloss(24,'C4 = Context, Containers, Components, Code. This context view shows users and the system boundary.')
gloss(25,'UML = Unified Modeling Language. Lanes show responsibility; diamonds branch or merge; arrows show order.')
gloss(26,'Multiplicity: 1 = exactly one; 0..* = zero or more. A release links conversations and goals to approved material.')
gloss(27,'Preflight = checks before publication. A transaction saves related changes together or rolls them back.')
gloss(28,'A goal is a persistent support objective. “Completed” is a record state, not proof of educational mastery.')
gloss(29,'Lexical = word matching. Hierarchical = evidence organised by level. Plan-observe = explicit retrieval steps.')
gloss(30,'C selects an action using proposal + lookahead; V checks that choice. Rejection returns no replacement.')
gloss(31,'Count = smoothed correct-attempt fraction; BKT = Bayesian Knowledge Tracing; PFA = Performance Factors Analysis.','Oracle = knows hidden need (upper bound); never = sends nothing. All conditions use the same eligibility rules.')
gloss(32,'Luna, Terra and Mini name the model allocations used in this study. Final wording includes fallback responses.','An effect interval including zero does not establish an improvement. Utility is a simulated decision score.')
gloss(33,'Visual retrieval selects a relevant figure or region. A grounded answer must also use its evidence correctly.','“Omni” labels the tested image-capable candidate. These are separate datasets, not a before/after trend.')
gloss(34,'Keep = retain; Refine = correct weaknesses; Go Deeper = investigate before release; Drop = reject the candidate.')
gloss(35,'A fold is a development/test subset. A correction narrows what an earlier run can validly establish.')
# Promote the causal and operational context previously available only during questions.
for n in [25,28,29,33]:
 old[n]['backup']=False
 old[n]['foot']=old[n]['foot'].replace('Backup diagram. Scope and notation are stated inside the figure.','Scope is stated inside the figure.').replace('Backup. ','')
edit(25,notes='The professor provides materials and settings, reviews the draft, and runs the preflight checks. Blockers return the work to revision. Publication creates the reviewed release that an authorised student can use. The lanes distinguish instructor decisions from application work and student access. A release is the published version to which later tutoring and goals are tied. This is why source review and publication are part of the software’s behaviour, rather than administrative background.')
edit(28,notes='A goal is a persistent support objective. It stays active while there is work to do. It can complete only when the exact target concepts satisfy the evidence rule, expire when its time ends, or be cancelled when its scope is invalidated. Hitting an attempt limit blocks further work but does not create a separate exhausted state. These are software lifecycle states. The completed label is not a validated claim of student mastery. This diagram explains what the observer and worker are maintaining between individual chats.')
edit(29,notes='These are the three factual paths that were tried. The lexical control retrieves by matching words, accepts an evidence hit, and extracts a source response. The hierarchy and plan-observe paths add organisation or explicit retrieval steps. Both eventually require coverage of the whole question. That shared check is the important failure location: it treated question-framing words as required evidence. The next table shows the resulting loss of answers on cases that were answerable. The comparison identifies a contract defect; it does not establish that hierarchical retrieval or planning is inherently inferior.')
edit(33,points=['Retrieving a relevant visual did not ensure a complete, supported answer.'],notes='Visual retrieval deserves a place in the main findings because richer source representation did not automatically improve the answer. In the historical comparison, relevant visual retrieval rose from eighteen to twenty-eight cases out of thirty, but grounded answers stayed at twenty. In a separate fresh image-capable comparison, the candidate produced sixteen grounded answers versus twenty-six for its control, and was dropped. These are separate studies. Their common lesson is that locating a relevant visual and turning it into a complete supported answer are different requirements.')
# Explicit methods before learner-model numbers.
ref=['research/05_evaluation/successor-learner-timing-simulation-001-results.md','src/digital_twin/student/learner_estimators.py','src/digital_twin/student/intervention_policies.py']
models=dict(title='Learner models and intervention timing',kind='table',sources=ref,
 rows=[['Component','Implemented meaning'],['Count baseline','(correct attempts + 1) / (all assessed attempts + 2); no forgetting'],['BKT: Bayesian Knowledge Tracing','Updates a known/unknown belief after each answer; models guessing, slips, learning and forgetting'],['PFA: Performance Factors Analysis','Logistic estimate using past successes and failures, weighted less as time passes'],['Constant / conditional timing','Send at eligible checks / send if stalled or estimated knowledge is low and uncertain'],['Value-based timing','Send only when estimated gain exceeds the configured margin']],widths=[385,775],
 gloss=['All estimators read assessed correctness and time, not raw text. The timing policy chooses whether to intervene.'],
 foot='Study E: 3 estimators × 3 timing policies, plus oracle and never-send bounds. No model-provider calls.',
 notes='Before reading the results, it helps to distinguish the estimator from the timing policy. The count baseline is a smoothed proportion of correct assessed attempts and does not forget. Bayesian Knowledge Tracing, or BKT, maintains a belief that a concept is known and updates it using correct or incorrect answers. Its model permits guessing, mistakes despite knowledge, learning, and forgetting over time. Performance Factors Analysis, or PFA, uses a logistic function of successes and failures with time decay. None of these methods reads the student’s text. They consume an assessed correctness record. Constant timing sends whenever the scheduled check is eligible. Conditional timing also requires a stalled or low-and-uncertain state. Value timing estimates the gain from intervening and requires it to exceed a margin. The experiment crosses the estimators and timing policies so their effects can be compared separately.')
method=dict(title='How learner estimation and timing were evaluated',kind='table',sources=ref,
 rows=[['Evaluation element','What was measured or controlled'],['Held-out learners','6 personas × 2 simulator families × 20 seeds = 240 per condition; 30 days, 8 concepts'],['Fit before testing','Parameters chosen on separate development seeds using next-answer log loss'],['Mean squared error (MSE) ↓','Daily mean of (estimated probability − hidden mastery)² over concept-days'],['Next-answer error: Brier ↓','Mean of (estimate before an attempt − observed 0/1 outcome)²'],['Intervention outcome','Messages, waste and final hidden mastery; 1,000 paired learner bootstrap resamples']],widths=[370,790],
 gloss=['Hidden mastery is available only to evaluation, not to the tested policy (except the oracle bound).','Bootstrap = resample learners to estimate uncertainty. These intervals do not establish real-student benefits.','Seed = reproducible random sequence; log loss penalizes confident wrong predictions.'],
 foot='Study E. All conditions share consent, quiet hours, a 3-message/7-day cap and a 24-hour same-concept cooldown.',
 notes='The held-out evaluation contains two hundred and forty learners per condition, formed from six personas, two simulator families, and twenty seeds. Parameters were selected on separate development seeds. Mean squared error compares each daily concept estimate with the simulator’s hidden mastery. The Brier score instead compares the estimate just before an assessed attempt with the observed correct or incorrect outcome. These are different evaluation targets. Messages and waste measure intervention behaviour. Waste means sending when hidden mastery is already at least zero point eight five, or when the learner is unreceptive. All methods face the same consent, quiet-hour and frequency restrictions. Paired bootstrap resampling gives uncertainty intervals across these simulated learners. The held-out split reduces seed overfitting, but does not remove dependence on the simulator’s assumptions.')
# Shorter narration avoids reading the new on-slide definitions twice.
edit(7,notes="The table reports the same development cases for three factual designs. Grounded means the answer contains the required supported claims. Answerable action means that the system answers when sufficient evidence is present. The lexical control answered every answerable case, although grounded accuracy was only about fifty-three percent. Both more complex paths fell to about twenty-five percent grounded accuracy, and answered only about thirty-six percent of answerable cases. They shared a whole-question coverage check that incorrectly required evidence for question-framing words. This is the concrete reason for the regression. Boundary handling remained perfect in this development comparison, so conservative abstention alone did not make the overall design useful. The next comparison changed the required-fact contract instead of adding another decision stage.")
edit(12,notes="The table separates the estimator from timing. With the count estimator fixed, conditional timing roughly halved the messages, but final simulated mastery also fell. Value timing retained more practice and reduced waste. BKT with value timing had lower hidden-state error and higher simulated final mastery than the count/constant control. However, the matched BKT-versus-count comparison under constant timing did not establish an improvement in next-answer Brier score: its interval includes zero. A better match to hidden simulator state is therefore not equivalent to better prediction of observed answers. All results depend on the simulated learning and receptivity rules. The full eleven-condition grid remains available in backup. BKT is an experimental candidate, not the default planner-input implementation. That integration distinction is the next finding.")
edit(14,notes="Both wording candidates preserved all fifty-six adequate drafts and repaired forty-seven of fifty-six defective drafts. Each still left one critical error, failing the zero-critical-error gate. The example is a necessary-versus-sufficient condition error. The source requires exactly two seals; an added example guarantees acceptance when two seals are present. The source does not support that guarantee. Structural compliance and fluent wording do not establish semantic correctness. The decision was not to promote either revision candidate. These were bounded, AI-assisted draft assessments, not evidence of student learning. The visual-retrieval comparison earlier showed a related boundary: improving an intermediate representation does not necessarily improve the final supported answer.")
edit(20,notes="Some historical scores cannot support the claims originally attached to them. A ten-thousand-case analysis exposed the reference answer during authoring, so it is not independent product-quality evidence. Another result has an unresolved aggregate contradiction and its unsupported grounded percentage is excluded. Round three exceeded the preregistered candidate limit, invalidating the selection claim while retaining useful diagnostics. The planner audit also separated preferred-label agreement from valid actions and utility. These corrections remain in the evidence record. They do not erase every result: the separately scoped typed-target, fresh factual, planner and lifecycle comparisons still support their stated conclusions. The point is to distinguish valid selection evidence from material that only explains a failure.")
old[12]['rows'].insert(4,['BKT + constant','0.035','14.0','46.4%','0.317'])
# Make the critical BKT result visible instead of leaving it in narration.
edit(12,points=['BKT reduced hidden-state error; next-answer improvement was inconclusive.','Conditional timing halved messages but also reduced simulated mastery.'],
 foot='Study E: 240 learners/condition. BKT vs count, constant timing: Brier change ≈ 0; 95% interval [−0.006, 0.006].')
# Define local wording rather than silently relying on letters and score names.
edit(8,title='Explicit required facts helped; extra ranking did not')
edit(32,foot='Model allocation study: Luna = GPT-5.6 Luna; Terra = GPT-5.6 Terra; Mini = GPT-5.4 Mini. Separate studies above.')
# Keep the actual demonstration on slide 3 so the existing native-media attachment is stable.
order=[1,2,3,25,4,5,28,6,29,7,8,9,33,10,11,'models','method',12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,30,31,32,34,35]
new=[]
for k in order:new.append(deepcopy(models if k=='models' else method if k=='method' else old[k]))
q=next(i for i,s in enumerate(new) if s['kind']=='questions')
for i,s in enumerate(new,1):
 s['number']=i;s['backup']=i>q+1
 # Include on-slide definitions in notes for accessible reading too.
 if s.get('gloss'):s['notes']+='\n\nTerminology on this slide: '+' '.join(s['gloss'])
d.update(slides=new,main_slides=q,main_word_count=sum(len(re.findall(r"\b[\w’'-]+\b",s['notes'].split('\n\nTerminology')[0])) for s in new[:q]))
P.write_text(json.dumps(d,indent=2))
script=['# English presentation script — informative revision','',f'{q} main slides, Questions, {len(new)-q-1} backup slides. Video: 4:06.','',f"Narration: approximately {d['main_word_count']} words excluding repeated terminology blocks. At 170 words/min plus video: {d['main_word_count']/170+4.1:.1f} minutes before transitions. Rehearse to verify timing.",'']
for s in new:script.extend([f"## {s['number']}. {s['title'].replace(chr(10),' ')}",'',s['notes'],'','Sources: '+', '.join(s['sources']),''])
Path('reports/presentation/speaker-script-informative.md').write_text('\n'.join(script))
print(len(new),'slides;',q,'main;',d['main_word_count'],'words')
